Repository O-X-L/ansible-opnsense, pull requests merged in 2025-05, with the labels that each got.

#214 Problem: OpenVPN Client/Server not working after changes to search API
  plugins/module_utils/base/base.py
  plugins/module_utils/main/ipsec_manual_spd.py
Labels: api-fix

#220 test: keep running tests if some fail & show overall test-results
  scripts/test.sh
Labels: enhancement

#195 WIP: add match_fields to PreSharedKey module
  docs/source/modules/ipsec.rst
  plugins/modules/ipsec_psk.py
  tests/1_cleanup.yml
  tests/ipsec_psk.yml
Labels: enhancement

#230 fix: webproxy_cache api-fixes
  plugins/module_utils/main/webproxy_cache.py
  plugins/modules/webproxy_cache.py
  tests/webproxy_cache.yml
Labels: bug, api-fix

#233 fix: New search api forces detail call on all items
  plugins/module_utils/base/base.py
  plugins/module_utils/base/cls.py
  plugins/module_utils/main/ipsec_cert.py
Labels: bug, api-fix
