Repository O-X-L/ansible-opnsense, pull requests merged in 2025-09, with the labels that each got.

#289 docs: move TOC to the left for more content-space
  docs/source/conf.py
Labels: documentation

#240 First attempt at creating dnsmasq module for opnsense
  docs/source/modules/dnsmasq.rst
  meta/runtime.yml
  plugins/module_utils/main/dnsmasq_general.py
  plugins/modules/dnsmasq_general.py
  plugins/modules/list.py
  plugins/modules/reload.py
  plugins/modules/service.py
  tests/dnsmasq_general.yml
Labels: enhancement

#290 Housekeeping
  README.md
  docs/source/_include/head.rst
  docs/source/modules/3_raw.rst
  docs/source/modules/access.rst
  docs/source/modules/acmeclient.rst
  docs/source/modules/bind.rst
  docs/source/modules/cron.rst
  docs/source/modules/frr_bfd.md
  docs/source/modules/frr_bgp.md
  docs/source/modules/frr_general.md
  docs/source/modules/frr_ospf.md
  docs/source/modules/frr_rip.md
  docs/source/modules/hasync.rst
  docs/source/modules/ids.rst
  docs/source/modules/ipsec.rst
  docs/source/modules/nat_one_to_one.rst
  docs/source/modules/nat_source.rst
  docs/source/modules/nginx.rst
  docs/source/modules/package.rst
  docs/source/modules/postfix.rst
  docs/source/modules/rule.rst
  docs/source/modules/service.rst
  docs/source/modules/shaper.md
  docs/source/modules/snapshot.rst
  docs/source/modules/syslog.rst
  docs/source/modules/system.rst
  docs/source/modules/unbound_acl.rst
  docs/source/modules/unbound_general.md
  plugins/module_utils/base/base.py
  plugins/module_utils/main/gateway.py
Labels: chore

#304 Feature: Add ipsec_general module
  README.md
  docs/source/modules/ipsec.rst
  meta/runtime.yml
  plugins/module_utils/main/ipsec_cert.py
  plugins/module_utils/main/ipsec_connection.py
  plugins/module_utils/main/ipsec_general.py
  plugins/module_utils/main/ipsec_pool.py
  plugins/module_utils/main/ipsec_vti.py
  plugins/modules/ipsec_cert.py
  plugins/modules/ipsec_connection.py
  plugins/modules/ipsec_general.py
  plugins/modules/ipsec_pool.py
  plugins/modules/ipsec_vti.py
  plugins/modules/list.py
  scripts/test.sh
  tests/1_cleanup.yml
  tests/ipsec_cert.yml
  tests/ipsec_connection.yml
  tests/ipsec_general.yml
  tests/ipsec_pool.yml
  tests/ipsec_vti.yml
Labels: enhancement

#305 test: update ci for integration-tests on pr's
  .github/workflows/functional_test_pr.yml
  .github/workflows/lint-ansible.yml
  .github/workflows/lint-python.yml
  .gitignore
  README.md
Labels: CI
