Repository O-X-L/ansible-opnsense, pull requests merged in 2025-04, with the labels that each got.

#207 Fix bgp general redistribute
  .github/FUNDING.yml
  README.md
  docs/source/modules/frr_bgp.md
  plugins/module_utils/main/frr_bgp_general.py
  plugins/modules/frr_bgp_general.py
  tests/frr_bgp_general.yml
Labels: api-fix

#205 Feature: Snapshot management
  README.md
  docs/source/modules/snapshot.rst
  meta/runtime.yml
  plugins/module_utils/main/snapshot.py
  plugins/modules/list.py
  plugins/modules/snapshot.py
  scripts/test.sh
  tests/1_cleanup.yml
  tests/snapshot.yml
Labels: enhancement

#200 add 'description' field to ansibleguy.opnsense.unbound_forward module
  plugins/module_utils/main/unbound_forward.py
  plugins/modules/unbound_forward.py
  tests/1_cleanup.yml
  tests/unbound_forward.yml
Labels: enhancement

#210 fix: add link_servers/link_peers fields to wireguard modules (#150)
  docs/source/modules/wireguard.md
  plugins/module_utils/main/wireguard_peer.py
  plugins/module_utils/main/wireguard_server.py
  plugins/modules/wireguard_peer.py
  plugins/modules/wireguard_server.py
  tests/wireguard_peer.yml
  tests/wireguard_server.yml
Labels: bug
